version: 2

updates:
  # Enable version updates for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    reviewers:
      - "opencsms/core-team"
    assignees:
      - "opencsms/core-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "org.springframework.boot"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework"
        update-types: ["version-update:semver-major"]
      # Ignore patch updates for test dependencies
      - dependency-name: "*"
        dependency-type: "development"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for Docker base images
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
      - "opencsms/devops-team"
    assignees:
      - "opencsms/devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # Only security updates for major versions
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
      - "opencsms/devops-team"
    assignees:
      - "opencsms/devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"